/* Copyright (c) 2008-2018, Quantcast Corp. */
/* Version: 2ce9ef4-20180710123726 */
window.__qc=function(c){if(c.__qc)return c.__qc;var wa="a ce cm dst enc fpa fpan je ns ogl rf tzo sr".split(" "),N,$a=["9591ee0951f"],x=c.document,C=c.navigator,ca="4dcfa7079941 127fdf7967f31 588ab9292a3f 32f92b0727e5 22f9aa38dfd3 a4abfe8f3e04 18b66bc1325c 958e70ea2f28 bdbf0cb4bbb 65118a0d557 40a1d9db1864 18ae3d985046 3b26460f55d".split(" "),xa=!1,ya=!1,da=0,ea=[],ab=[],O=[],z=[],G={},P=0,D=null,fa={},q={},za=null,p,l,B,H,Aa=!1,ga=!1,E=null,ha=[].slice,Ba,ia,Q,f,A,ja,Ca,Da,ka,Ea,I,la,J,R,Fa,ma,na,
Ga,Ha,K,Ia,oa,Ja,Ka,La,Ma,Na,Oa,S,T,U,k,Pa,w,Qa,V,Ra,Sa,pa,Ta,qa,W,y,Ua,L,Va,X,Wa,Xa,Y,Ya,ra,sa,Za,ta,F,Z,aa,M,ua,va,ba;(function(){var a;a=x.createElement("script");N="async"in a?1:a.readyState?2:3})();var u=function(a){try{return{init:R,hash:J,push:Fa,rules:Wa,hasRules:Y,defaults:Za,__qc:function(){return!0}}[a].apply(null,ha.call(arguments,1))}catch(b){return!1}};u.evts=0;u.v=2;u.SD=ca;u.qpixelsent=[];X=function(a){var b=a?a.length||0:0,d;for(d=0;d<b;d++)if(!a[d])return!1;return!0};sa=function(a){(a=
a||c._qacct)&&(W(z,a)||z.push(a))};W=function(a,b){var d=a.length,c;for(c=0;c<d;c++)if(a[c]===b)return!0;return!1};L=function(a){return{}.toString.call(a).match(/\s([a-zA-Z]+)/)[1].toLowerCase()};Va=function(a){var b,d;b=L(a);if("array"===b)return a.slice(0);if("object"===b){b={};for(d in a)a.hasOwnProperty(d)&&(b[d]=a[d]);return b}return"string"===b?""+a:a};Fa=function(a,b){k(a,b)};Y=function(a){return W(O,a)};Za=function(a,b){var d;a&&((d=fa[a])&&(b=M(b,d)),b.qacct&&delete b.qacct,fa[a]=b)};ta=
function(a){var b,d;if(f(a))for(b in a)if("string"==typeof a[b]){b=a.event||"load";d=a.media||"webpage";"rule"!==b&&"load"!==b||"webpage"!==d&&"ad"!==d?k(a):(d=a.qacct||c._qacct,a.qacct=d,b=(b=q[d])?M(b,a):a,q[d]=b);sa(a.qacct);break}else"object"==typeof a[b]&&null!=a[b]&&ta(a[b])};M=function(a,b){var d={};d.qacct=a.qacct||b.qacct;d.event="load"===a.event||"load"===b.event?"load":a.event&&b.event?a.event||b.event:null;d.media=null;d.media="webpage"===a.media||"webpage"===b.media?"webpage":"ad"===
a.media||"ad"===b.media?"ad":a.media||b.media;pa(d,a,b);pa(d,b,a);d.event||delete d.event;d.media||delete d.media;return d};pa=function(a,b,d){var c,e,h,r,f,m;for(c in b)b.hasOwnProperty(c)&&!a.hasOwnProperty(c)&&(e=b[c],h=d[c],r="",f=!!e&&"string"==typeof e,m=!!h&&"string"==typeof h,f&&(r=e),f&&m&&(r+=","),m&&(r+=h),a[c]=r)};F=function(){var a=[],b,d;if(!(0<P)){Ua();for(b in q)q.hasOwnProperty(b)&&q[b]&&(d=q[b],a.push(d),delete q[b]);1==a.length&&k(a[0]);1<a.length&&k(a)}};Z=function(){var a=[],
b,d,c;c=z.slice(0);for(b=0;b<c.length;b++)d=c[b],Y(d)||a.push(d);if(0===a.length)F();else for(b=0;b<a.length;b++)d=a[b],O.push(d),Ta(d)};qa=function(a,b,d,v){var e;a=c.location.protocol+"//"+a;D=D||x.scripts[0];e=x.createElement("script");if(1===N)e.src=a,e.async=!0,e.onload=b,d&&(e.onerror=d),D.parentNode.insertBefore(e,D);else if(2===N){var h=!1;e.onload=e.onreadystatechange=function(){h||"loaded"!=e.readyState&&"complete"!=e.readyState||(h=!0,e.onreadystatechange=null,b())};e.src=a;D.parentNode.insertBefore(e,
D)}else v&&v()};Ta=function(a){P++;qa("rules.quantcount.com/rules-"+a+".js",function(){G[a]=2===N?2:0;aa()},function(){G[a]=1;aa()},function(){G[a]=4;aa()})};aa=function(){P-=0<P?1:0;F()};Wa=function(){var a=!0,b,d,c;if(arguments.length){c=function(b){a?ta(b):k(b,!0)};for(b=0;b<arguments.length;b++)d=ha.call(arguments[b],0),d.splice(1,0,c),Xa.apply(null,d);a=!1;xa&&F()}};Xa=function(a,b){var d=[],c=[],e=b||k,h,f,t,m,n;if((h=ha.call(arguments,2))&&h.length){f=h[0]||X;t=h[1];m=h[2];h=m.length;for(n=
0;n<h;n++)d.push(!1),c.push(null);d={p:a,f:d,r:f,c:m,a:t,v:c};Y(a)||O.push(a);ab.push(d);Ya(d,e)}else O.push(a),G[a]=6};Ya=function(a,b){var d=a?a.c?a.c.length:0:0,c;for(c=0;c<d;c++)(function(d){var c,e;try{c=a.c[d][0],e=a.c[d].slice(1),e.splice(0,0,function(c){a.f[d]=!0;a.v[d]=c;ra(a,b)}),c.apply(null,e)}catch(t){a.f[d]=!0,a.v[d]=!1,ra(a,b)}})(c)};ra=function(a,b){var d=a.a,c=a.v,e=a.r||X,h,f,t,m,n,g;(h=X(a.f))&&(h=h&&e(c));if(h)for(c=0;c<d.length;c++)try{f=d[c][0];t=1<d[c].length?d[c].slice(1):
[];t=t.concat(a.v);m=f.apply(null,t);n={qacct:a.p,event:"rule"};for(g in m)m.hasOwnProperty(g)&&"qacct"!==g&&(n[g]=m[g]);b(n)}catch(bb){}};Ba=function(){return ia(0)!==ia(6)?1:0};ia=function(a){a=new Date(2E3,a,1,0,0,0,0);var b=a.toGMTString(),b=new Date(b.substring(0,b.lastIndexOf(" ")-1));return a-b};Q=function(a){return a.replace(/\./g,"%2E").replace(/,/g,"%2C")};A="function"===typeof encodeURIComponent?encodeURIComponent:Q;f=function(a){return"undefined"!=typeof a&&null!=a};ja=function(){return Math.round(2147483647*
Math.random())};Ca=function(a){var b="",d=x.cookie,c;if(!d)return b;c=d.indexOf(a+"=");a=c+a.length+1;-1<c&&(b=d.indexOf(";",a),0>b&&(b=d.length),b=d.substring(a,b));return b};Ga=function(a){return"P0-"+ja()+"-"+a.getTime()};na=function(a,b,d){return["__qca=",a,"; expires=",b.toGMTString(),"; path=/; domain=",d].join("")};ma=function(){var a=["",""],b=I(),d,c;if(1===da)return a[0]=";fpan=u;fpa=",a;d=J(b);for(c=0;c<ca.length;c++)if(ca[c]===d)return a[0]=";fpan=u;fpa=",a;d=new Date;c=Ca("__qca");0<
c.length||E?(0===c.length&&(c=E,a[1]=na(E,new Date(d.getTime()+338688E5),b)),a[0]=";fpan=0;fpa="+c):(E=Ga(d),a[1]=na(E,new Date(d.getTime()+338688E5),b),a[0]=";fpan=1;fpa="+E);return a};Da=function(){var a=ma()[1];a&&(x.cookie=a)};ka=function(a){x.cookie=a+"=; expires=Thu, 01 Jan 1970 00:00:01 GMT; path=/; domain="+I()};I=function(){var a,b,d,c;a=x.domain;"www."===a.substring(0,4)&&(a=a.substring(4,a.length));b=a.split(".");c=b.length;if(3>c)return a;d=b[c-1];return 3>d.length?a:a=b[c-2]+"."+d};la=
function(a,b){var d;for(d=0;d<b.length;d++)a^=b.charCodeAt(d),a+=(a<<1)+(a<<4)+(a<<7)+(a<<8)+(a<<24);return a};J=function(a){var b;b=la(2166136261,a);a=la(3386659096,a);return Math.round(Math.abs(b*a)/65536).toString(16)};Ra=function(a){var b,d;if(a&&"object"===L(a))for(d=0;d<wa.length;d++)b=wa[d],a.hasOwnProperty(b)&&a[b]&&delete a[b]};V=function(a,b,d){var v={},e,h=null,r="webpage",t="load",m={},n,g;e=b?b.qacct||c._qacct:c._qacct;n=q[e];b?n&&(b=M(b,n)):b=n;e&&delete q[e];Ra(b);if(null!=b)for(g in b)m[g]=
void 0!==b[g],b.hasOwnProperty(g)&&"string"===typeof g&&"string"===typeof b[g]&&("uid"===g||"uh"===g?(Ha()||(h=J(b[g])),delete b[g]):"qacct"!==g&&(0<b[g].length?v[g+a]=A(b[g]):m[g]=!1,"media"===g&&(r=b[g]),"event"===g&&(t=b[g])));if("string"!==typeof e){if(!f(c._qacct)||0===c._qacct.length)return null;e=c._qacct}if(e){if(n=fa[e])for(g in n)"string"===typeof g&&n.hasOwnProperty(g)&&!m[g]&&(v[g+a]=A(n[g]),"media"===g&&(r=n[g]),"event"===g&&(t=n[g]))}else return null;m=G[e];f(m)||(m=3);v["rf"+a]=""+
m;"string"===typeof h&&(b.uh=h,v["uh"+a]=A(h));if("webpage"===r&&"load"===t){for(b=0;b<u.qpixelsent.length;b++)if(u.qpixelsent[b]===e&&!d)return null;u.qpixelsent.push(e)}"ad"===r&&(da=1);v["a"+a]=e;return v};Qa=function(a){var b=[],d;for(d in a)a[d]&&a.hasOwnProperty(d)&&b.push(d+"="+a[d]);return b.join(";")};Sa=function(){var a=x.getElementsByTagName("meta"),b="",d,c,e,h;for(d=0;d<a.length;d++){e=a[d];if(1E3<=b.length)return b;f(e)&&f(e.attributes)&&f(e.attributes.property)&&f(e.attributes.property.value)&&
f(e.content)&&(c=e.attributes.property.value,e=e.content,3<c.length&&"og:"===c.substring(0,3)&&(0<b.length&&(b+=","),h=80<e.length?80:e.length,b+=Q(c.substring(3,c.length))+"."+Q(e.substring(0,h))))}return A(b)};Ea=function(a){return"object"===typeof a?["p","approved"===a.consent?"a":"d","asserted"===a.source?"e":"i"].join(""):""};Ha=function(){var a=!1;f(c.external)&&(a=c.external,a="function"===typeof a.InPrivateFilteringEnabled&&!0===a.InPrivateFilteringEnabled());return a||"1"==C.doNotTrack||
"yes"===C.doNotTrack||"1"==C.msDoNotTrack};k=function(a,b){var d="function"===typeof encodeURIComponent?"n":"s",v=ja(),e="",h="",r="",t="",m="",n="u",g="1",p=[],l,k,q,y,z;da=0;f(u.qpixelsent)||(u.qpixelsent=[]);if(f(a))if(l=L(a),"object"===l)k=V("",a,b);else{if("array"===l)for(l=0;l<a.length;l++)q=V("."+(l+1),a[l],b),k=0===l?q:M(k,q)}else"string"===typeof _qacct&&(k=V("",null,b));k&&(l=C.cookieEnabled?"1":"0","undefined"!=typeof C.javaEnabled&&(n=C.javaEnabled()?"1":"0"),f(c._qmeta)&&(h=";m="+A(c._qmeta),
c._qmeta=null),self.screen&&(e=screen.width+"x"+screen.height+"x"+screen.colorDepth),q=new Date,y=Ba(),z=ma()[0],c.location&&c.location.href&&(r=A(c.location.href)),x&&x.referrer&&(m=A(x.referrer)),c.self===c.top&&(g="0"),k.url?t=r:k.url=r,k.ref||(k.ref=m||""),r=Sa(),m=Qa(k),p.push("/pixel;r="+v+";"+m+z+";ns="+g+";ce="+l+";qjs=1;qv=2ce9ef4-20180710123726"),p.push((k.ref?"":";ref=")+";je="+n+";sr="+e+";enc="+d+";dst="+y+";et="+q.getTime()+";tzo="+q.getTimezoneOffset()+(t?";ourl="+t:"")+h+";ogl="+r),
ea.push(p),w())};Pa=function(a){if(l){var b=new Image;a=[c.location.protocol,"//pixel.",Ia(p)?"quantserve.com":"quantcount.com",a[0],";cm=",Ea(p),f(B)&&""!==B?";gdpr=1;gdpr_consent="+B:"",a[1]].join("");b.alt="";b.src=a;b.onload=function(){b&&"number"==typeof b.width&&3===b.width?ka("__qca"):Da()}}};w=function(){if(p&&f(l)&&f(B))for(l||ka("__qca");ea.length;)Pa(ea.shift());else La()};Ia=function(a){return!0===a||1===a||1===a||f(a)&&"approved"===a.consent?!0:!1};Oa=function(a){if(!a)return!1;for(a=
0;a<z.length;a++)if(W($a,J(z[a])))return!0;return!1};La=function(){Aa||(Aa=!0,c.top===c.self?("function"===typeof __cmp?__cmp("getVendorConsents",[11],function(a,b){S(a,b);__cmp("getConsentData",1,T)}):oa(),"object"===typeof PrivacyManagerAPI&&"function"===typeof PrivacyManagerAPI.callApi?Ja("getConsent","advertising"):p=!0):c.postMessage&&"object"===typeof c.JSON?Ka("getConsent","advertising"):(p=1,l=!1),w())};Ja=function(a,b){p=PrivacyManagerAPI.callApi(a,"quantserve.com",I(),"truste.com",b);w()};
Ka=function(a,b){for(var d=window;!H;){try{d.frames.__cmpLocator&&(H=d)}catch(v){}if(d===window.top)break;d=d.parent}if(H)try{H.postMessage(c.JSON.stringify({__cmpCall:{command:"getVendorConsents",parameter:[11],callId:1}}),"*")}catch(v){l=!1}else oa();if(c.addEventListener)c.addEventListener("message",K,!1);else if(c.attachEvent)c.attachEvent("onmessage",K);else return p=!0,ga||f(l)||(l=!1),w();try{c.top.postMessage(c.JSON.stringify({PrivacyManagerAPI:{timestamp:(new Date).getTime(),action:a,self:"quantserve.com",
domain:I(),authority:"truste.com",type:b}}),"*")}catch(v){p=1}f(p)||(za=setTimeout(function(){f(p)||(p=!0,w())},25));w()};oa=function(){c.__qcu||(ga=!0,qa("quantcast.mgr.consensu.org/qcu.js",function(){"function"===typeof c.__qcu&&c.__qcu("getCurrentVendorConsents",[11],function(a,b){S(a,b);c.__qcu("getConsentData",null,T)})},function(){l=!1;w()},function(){l=!1;w()}))};K=function(a){if("string"===typeof a.data&&0!==a.data.length){var b;try{b=c.JSON.parse(a.data)}catch(d){return}if(b.__cmpReturn)return Ma(b.__cmpReturn);
Na(b)}};Na=function(a){a&&"object"===typeof a.PrivacyManagerAPI&&(clearTimeout(za),U(),p=a.PrivacyManagerAPI,w())};Ma=function(a){1===a.callId?(S(a.returnValue,a.success),H.postMessage(c.JSON.stringify({__cmpCall:{command:"getConsentData",parameter:null,callId:2}}),"*")):2===a.callId&&T(a.returnValue,a.success)};T=function(a,b){B=b?a.consentData||"":"";U();w()};S=function(a,b){var c=a.gdprApplies,f=a.metadata,e=a.vendorConsents,e=e?e[11]:void 0,h=a.purposeConsents,k;h&&(k=h[1]);"boolean"!==typeof c?
l=!1:ga&&null===f?(l=!Oa(c),B=""):l=b&&(!c||e&&k);U();w()};U=function(){f(l)&&f(p)&&f(B)&&(c.removeEventListener?window.removeEventListener("message",K,!1):c.detachEvent&&window.detachEvent("onmessage",K))};ua=function(){var a=arguments,b,c;y([].slice.call(a));for(c=0;c<a.length;c++)b=a[c],k(b);z.length?Z():F()};y=function(a){var b=L(a);if("array"===b)for(b=0;b<a.length;b++)y(a[b]);else"object"===b&&sa(a.qacct||c._qacct)};Ua=function(){var a;ya||c._qevents.length||c.ezt.length||"undefined"===typeof _qacct||
(k({qacct:c._qacct}),ya=!0);if(!u.evts){for(a in c._qevents)c._qevents[a]!==c._qevents.push&&c._qevents.hasOwnProperty(a)&&k(c._qevents[a]);for(a in c.ezt)c.ezt[a]!==c.ezt.push&&c.ezt.hasOwnProperty(a)&&k(c.ezt[a]);c._qevents={push:ua};c.ezt.push=function(){var a=arguments,d;if(f(c.queueManager))for(d=0;d<a.length;d++)c.queueManager.push(a[d]);else ua.apply(this,arguments)};u.evts=1}};ba=function(a){var b;a&&(b=Va(a),y(a),c._qevents.push(b))};va=function(a){a.push=function(){y([].slice.call(arguments));
Z();return[].push.apply(a,arguments)}};R=function(){f(c._qevents)||(c._qevents=[]);f(c.ezt)||(c.ezt=[]);ba(c._qoptions);ba(c.qcdata);ba(c.smarttagdata);u.evts||(va(c._qevents),va(c.ezt));y(c.ezt);y(c._qevents);y({qacct:c._qacct});c._qoptions=null;z.length?Z():F();xa=!0};c.quantserve=c.quantserve||R;u.quantserve=R;return u}(window);quantserve();
