(function(e,l,A,u){var p=function(){function c(b){if(b&&g.O(b)){var f={name:null,w:null,f:null};if(0<=b.indexOf(".")){b=b.split(".",2);var c=b[0];b=b[1];if(!d[c])return;f.w=c}if(0<=b.indexOf(":")){b=b.split(":",2);c=b[0];b=b[1];if(!a[c])return;f.f=c}if(f.f||z.prototype[b])return f.name=b,f}}var a={},d={},b={create:function(b,a,c){if(!b)return!1;a=a||b;if(d[a])return!1;d[a]=new z(b,a,c);return!0},exec:function(b){var f=Array.prototype.slice.call(arguments,1);if("exec"===b)return!1;if(p[b])return p[b].apply(null,
f);var n=c(b);if(!n)return!1;var k=a[n.f];if(g.isArray(k))return a[n.f].push(Array.prototype.slice.call(arguments,0)),!0;if(k&&!k[n.name])return!1;for(var e=n.w?[d[n.w]]:g.values(d),r=f.length&&g.o(f[-1])?f[-1].callback:u,t=g.H(),v=!0,l=0;l<e.length;l++){var m=e[l];r&&(f[-1].callback=t.B());v=(k||m)[n.name].apply(m,f)&&v}t.complete(r);return v},get:function(b,a){a=a||g.c;"identity"===b&&w.N(m.b(function(b){a(b)}))},register:function(b,d){if(!a[b]||!g.j(d))return!1;var c=a[b];a[b]=d();setTimeout(function(){for(var b=
0;b<c.length;b++)p.exec.apply(null,c[b])});return!0},require:function(b){if(a[b])return!1;a[b]=[];x.fa("/plugins/"+b+".js");return!0},set:function(a,d){b.h=b.h||function(b,a){p.exec("associate",b,{callback:a})};switch(a){case "captureEmailForms":d?y.C(b.h):y.da(b.h)}}};return b}(),y=function(){function c(){n=function(){l.addEventListener("submit",h,!1);setTimeout(function(){l.removeEventListener("submit",h,!1)});return!0};l.addEventListener("submit",n,!0);l.addEventListener("click",b,!0)}function a(b){var a=
/\S+@\S+.\S/;b=b.getElementsByTagName("input");for(var d,h=0;h<b.length;h++)if(d=b[h],!d.hasAttribute("center-ignore")&&(d.hasAttribute("center-associate-email")||"email"===d.type||0<=d.name.toLowerCase().replace(/[^a-z]+/gi,"").indexOf("email")||0<=d.id.toLowerCase().replace(/[^a-z]+/gi,"").indexOf("email")||0<=d.className.toLowerCase().replace(/[^a-z]+/gi,"").indexOf("email")))return a.test(d.value)?d.value:null;return null}function d(b,d){function h(){if(!b.G){b.G=!0;if(d){var a=l.createElement("input");
a.type="hidden";for(var c=["name","value"],f=0;f<c.length;f++){var k=a,g=c[f],e=void 0,e=e||g,g=d.getAttribute(g);null!==g&&k.setAttribute(e,g)}b.appendChild(a);a=["action","enctype","method","novalidate","target"];for(c=0;c<a.length;c++)f=b,e="form"+a[c],k=(k=a[c])||e,e=d.getAttribute(e),null!==e&&f.setAttribute(k,e)}HTMLFormElement.prototype.centerOldSubmit.call(b)}}try{for(var c=a(b),f=g.H(),k=0;k<m.length;k++)m[k].call(null,c,f.B());f.complete(h)}catch(e){h()}setTimeout(h,2E3)}function b(b){var a=
b.target;if(a&&0<="INPUT BUTTON".indexOf(a.tagName)&&0<="submit image button".indexOf(a.type)){b=b.target;a=b;if(a.form)a=a.form;else for(;a&&"FORM"!==a.tagName;)a=a.parentElement;a&&!a.hasAttribute("center-ignore")&&(a.centerActor=b)}}function h(b){if(!1!==b.returnValue&&!b.defaultPrevented){var c=b.target;if(c&&!c.hasAttribute("center-ignore")&&a(c))return d(c,c.centerActor),b.preventDefault(),!1}}function f(){HTMLFormElement.prototype.centerOldSubmit=HTMLFormElement.prototype.submit;HTMLFormElement.prototype.submit=
function(){if(this.hasAttribute("center-ignore")||!a(this))return HTMLFormElement.prototype.centerOldSubmit.call(this);d(this,null)}}var n,k=!1,m=[];return{C:function(b){!k&&l.addEventListener&&e.HTMLFormElement&&!k&&(c(),f(),k=!0);m.push(b)},da:function(a){a=m.indexOf(a);-1<a&&m.splice(a,1);!m.length&&k&&k&&(l.removeEventListener("submit",n,!0),l.removeEventListener("click",b,!0),HTMLFormElement.prototype.submit=void 0,k=!1)}}}(),x=function(){return{F:function(c,a,d){d=d||g.c;var b={method:"GET"};
b.url="https://api.leadpages.io"+c+"?"+g.R(a);var h=new XMLHttpRequest;"withCredentials"in h?(h.open(b.method,b.url,!0),h.withCredentials=!0,h.onreadystatechange=function(){4===h.readyState&&(b.code=h.T,400<=h.status?d(h.responseText,b):d(null,b))},h.ontimeout=function(){b.T=0;d("TIMEOUT",b)},h.send()):(c=new Image,g.D(c,"load",function(){d(null,b)}),c.src=b.url)},fa:function(c){var a=l.createElement("script");a.async=!0;a.src="https://js.center.io"+c;l.getElementsByTagName("head")[0].appendChild(a)}}}(),
m=function(){var c=[],a={flush:function(){if(c.length){for(var a=[],b=[],h=[],f=0;f<c.length;f++)a.push(c[f].kind),b.push(c[f].label),h.push(c[f].value);c.length=0;a={version:"1.7.13",correlateBy:g.K("center-correlate-by")||g.L(),origin:"center-js",kind:a,label:b,value:h};x.F("/analytics/v1/observations/capture",a)}},g:function(d,b,h){c.push({kind:d,label:b,value:h});a.A=a.A||g.U(a.flush,4E3,!1);a.A()},u:function(d,b){if(e.performance&&e.performance.getEntriesByName){var c=performance.getEntriesByName(b)[0];
c&&c.duration&&a.g("timer",d,c.duration)}},ca:function(d){if(!(e.performance&&e.performance.mark&&e.performance.measure&&e.performance.getEntriesByName))return g.c;var b="center-"+d+"-s",c="center-"+d+"-e",f="center-"+d;performance.mark(b);return function(){performance.mark(c);performance.measure(f,b,c);a.u(d,f)}},P:function(d){if(d)try{var b={uid:g.i("centerVisitorId")||"",url:q.M(),ua:navigator.userAgent,n:(d.name||"").substr(0,100),m:(d.message||"").substr(0,100),s:(d.stack||"").replace(/\s+/gi,
" ").substr(0,500)};a.g("text","error",g.R(b));a.flush()}catch(c){}},b:function(d,b){b=b||e;return function(){try{return d.apply(b,arguments)}catch(c){a.P(c)}}},ga:function(d){for(var b in d)d.hasOwnProperty(b)&&g.j(d[b])&&(d[b]=a.b(d[b],d))}};return a}(),q=function(){return{V:function(){return{x:e.innerWidth||(l.documentElement||{}).clientWidth||(l.body||{}).clientWidth||0,y:e.innerHeight||(l.documentElement||{}).clientHeight||(l.body||{}).clientHeight||0}},W:function(){return l.referrer},X:function(c){function a(a){a=
Math.abs(Math.floor(a));return(10>a?"0":"")+a}c=c||new Date;c=-c.getTimezoneOffset();return(0<=c?"+":"-")+a(c/60)+":"+a(c%60)},M:function(){return e.location.toString().replace(/ /g,"%20")},Y:function(){var c=g.J(q.Z());(c=c.utm_email||c.center_email||c.email||c.wemail||u)&&(c=c.replace(/ /g,"+"));return c},Z:function(){return e.location.search||""}}}(),z=function(){function c(b,d,c){var n=this;n.ba=b;n.name=d;n.options=g.I(c||{},a);e.fbq&&(b=l.querySelector('meta[name="fb-pixel-id"]'))&&b.content&&
(n.options.facebookPixelId=b.content);n.options.captureEmailForms&&y.C(function(b,a){n.associate(b,{callback:a})});n.options.captureEmailURLs&&(b=q.Y())&&n.associate(b)}var a={captureEmailForms:!1,captureEmailURLs:!0,customId:""},d={view:"ViewContent",conversion:"Lead"};c.prototype.associate=function(b,a){a=a||{};a.email=b;return this.send("association",null,null,null,a)};c.prototype.send=function(a,c,f,n,k){var p=this,r={};r.callback=g.c;r.customId="";k=g.I(k||{},p.options,r);var t=k.callback;k.callback=
function(){try{k.facebookPixelId&&d[a]&&e.fbq("track",d[a],{referrer:l.referrer,userAgent:navigator.userAgent,language:navigator.language}),t()}catch(c){t()}};w.N(m.b(function(d){var e=q.V();d={k:a||"",a:c||"",l:f||"",v:n||"",e:k.email||"",pid:p.ba,uid:d.uid,sid:d.sid,cid:k.customId,uri:q.M().substr(0,1E3),rf:q.W().substr(0,500),rx:e.x,ry:e.y,tz:q.X()};x.F("/analytics/v1/events/capture",d,function(a,b){m.u("send-events",b.url);a?(m.P({name:"HTTPError",message:b.method+" "+b.url+" "+b.T,stack:a}),
m.flush(),k.callback(!1)):k.callback()})}));return!0};return c}(),g=function(){var c={D:function(a,d,b,c){a.addEventListener?a.addEventListener(d,b,c):a.attachEvent&&a.attachEvent("on"+d,b)},H:function(){return new function(){function a(){f>=c&&d&&!b&&(b=!0,d.call(e))}var d=null,b=!1,c=0,f=0;return{B:function(){c++;return function(){f++;setTimeout(a)}},complete:function(a){d=a}}}},U:function(a,d,b){function c(){var h=this,e=Array.prototype.slice.call(arguments,0),g=b&&!f;clearTimeout(f);f=setTimeout(function(){f=
null;b||a.apply(h,e)},d);g&&a.apply(h,e)}var f;c.clear=function(){clearTimeout(f);f=null};return c},I:function(a){var d=Array.prototype.slice.call(arguments,1);if(!d.length)return a;for(var b=0;b<d.length;b++)for(var c=d[b],f=g.keys(c),e=0;e<f.length;e++){var k=f[e];a[k]===u&&(a[k]=c[k])}return a},J:function(a){if(!g.O(a))return null;if(!a)return{};var d={};a=a.replace(/(^\?)/,"").split("&");for(var b=0;b<a.length;b++){var c=a[b].split("=");if(c[1]&&0<=c[1].indexOf(","))try{d[decodeURIComponent(c[0])]=
decodeURIComponent(c[1]).split(",")}catch(f){}else try{d[decodeURIComponent(c[0])]=decodeURIComponent(c[1])}catch(f){}}return d},forEach:function(a,d,b){if(Array.prototype.forEach)return Array.prototype.forEach.call(a,d,b);for(var c=0;c<a.length;c++)d.call(b,a[c],c,a)},G:function(a){return decodeURIComponent(l.cookie.replace(new RegExp("(?:(?:^|.*;)\\s*"+encodeURIComponent(a).replace(/[\-\.\+\*]/g,"\\$&")+"\\s*\\=\\s*([^;]*).*$)|^.*$"),"$1"))||null},K:function(a,d){d=d||e.location.search;var b=(new RegExp("[?&]"+
encodeURIComponent(a)+"(=([^&#]*)|&|#|$)")).exec(d);return b?b[2]?decodeURIComponent(b[2].replace(/\+/g," ")):"":null},ha:function(a){try{return localStorage.getItem(a)}catch(d){return null}},i:function(a){try{return sessionStorage.getItem(a)}catch(d){return null}},L:function(){return"xxxxxxxxxxxxxxxxxxxxxx".replace(/[x]/g,function(){return"23456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz".charAt(Math.floor(57*Math.random()))})},isArray:function(a){return!(!a||!a.constructor||a.constructor!==
Array)},j:function(a){return!(!a||"function"!==typeof a)},o:function(a){return!(!a||"object"!==typeof a)},O:function(a){return"string"===typeof a},keys:function(a){if(!g.o(a))return[];var d=[],b;for(b in a)a.hasOwnProperty(b)&&d.push(b);return d},ia:function(a){return Array.prototype.slice.call(a,0)},c:function(){},ea:function(a,d,b,c){a.removeEventListener?a.removeEventListener(d,b,c):a.detachEvent&&a.detachEvent("on"+d,b)},R:function(a){var d="",b;for(b in a)a.hasOwnProperty(b)&&(d+="&"+encodeURIComponent(b)+
"=",d=c.isArray(a[b])?d+encodeURIComponent(a[b]).replace(/%2C/g,","):d+encodeURIComponent(a[b]));return d.substr(1,d.length)},ja:function(a,d,b,c,f){l.cookie=encodeURIComponent(a)+"="+encodeURIComponent(d)+"; expires=Fri, 31 Dec 9999 23:59:59 GMT"+(b?"; domain="+b:"")+(c?"; path="+c:"")+(f?"; secure":"")},ka:function(a,d){try{return localStorage.setItem(a,d)}catch(b){return null}},S:function(a,d){try{return sessionStorage.setItem(a,d)}catch(b){return null}},values:function(a){if(!g.o(a))return[];
var d=[],b;for(b in a)a.hasOwnProperty(b)&&d.push(a[b]);return d}};return c}(),w=function(){function c(){for(var c=0;c<b.length;c++)b[c].call(e,{uid:d,sid:a});b.length=0}var a=null,d=null,b=[],h={$:function(a){var b=m.ca("load-identify"),c=l.createElement("iframe"),d=m.b(function(h){0==="https://js.center.io".indexOf(h.origin||(h.originalEvent||{}).origin)&&(h=g.J(h.data))&&h.s&&h.id&&(b(),g.ea(e,"message",d,!1),c.parentNode&&c.parentNode.removeChild(c),a(h))});g.D(e,"message",d,!1);c.src="https://js.center.io/identify.html";
c.style.display="none";c.style.visibility="hidden";c.style.position="absolute";c.style.left="-9999px";c.style.top="-9999px";l.getElementsByTagName("head")[0].appendChild(c)},aa:function(){a=g.i("centerSessionId");a||(a=g.L(),g.S("centerSessionId",a));(d=g.i("centerVisitorId"))?(m.g("counter","ident-cache","1"),c()):h.$(m.b(function(a){m.g("counter",a.s,"1");d=a.id;g.S("centerVisitorId",d);c()}))},N:function(c){d?c.call(e,{uid:d,sid:a}):b.push(c)}};return h}();m.ga(p);m.b(function(){if(null===g.K("center-no-load")){var c=
e[A]||"center";e[c]=e[c]||g.c;var a=e[c].q||[];e[c]=function(a){return g.j(a)?(a(e[c]),!0):p.exec.apply(p,arguments)};e[c].hash="40ab7e69ae694e2705c59ede5f0841be174644b9";e[c].version="1.7.13";e[c].loaded=!0;w.aa();for(var d=0;d<a.length;d++)e[c].apply(e[name],a[d]);m.u("load-center","https://js.center.io/center.js")}})()})(window,document,"LeadPagesCenterObject");
